# Generated by Django 6.0.3 on 2026-03-11 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('ciu_cdgo', models.AutoField(db_column='CIU_CDGO', primary_key=True, serialize=False)),
                ('ciu_tpodoc', models.CharField(db_column='CIU_TPODOC', max_length=32)),
                ('ciu_numdoc', models.CharField(db_column='CIU_NUMDOC', max_length=32, unique=True)),
                ('ciu_nmbres', models.CharField(db_column='CIU_NMBRES', max_length=128)),
                ('ciu_aplldos', models.CharField(db_column='CIU_APLLDOS', max_length=128)),
                ('ciu_fchancm', models.DateField(db_column='CIU_FCHANCM')),
                ('ciu_email', models.EmailField(blank=True, db_column='CIU_EMAIL', max_length=128, null=True)),
                ('ciu_tlfno', models.CharField(blank=True, db_column='CIU_TLFNO', max_length=32, null=True)),
                ('ciu_genro', models.CharField(db_column='CIU_GENRO', max_length=32)),
                ('ciu_etnia', models.CharField(blank=True, db_column='CIU_ETNIA', max_length=64, null=True)),
                ('ciu_nvleduc', models.CharField(blank=True, db_column='CIU_NVLEDUC', max_length=64, null=True)),
                ('ciu_ocpcion', models.CharField(blank=True, db_column='CIU_OCPCION', max_length=64, null=True)),
                ('ciu_discapacidad', models.BooleanField(db_column='CIU_DISCAPACIDAD', default=False)),
                ('ciu_estrato', models.IntegerField(blank=True, db_column='CIU_ESTRATO', null=True)),
                ('ciu_estdo', models.CharField(db_column='CIU_ESTDO', default='A', max_length=1)),
            ],
            options={
                'db_table': 'ciu_ciudadano',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaValor',
            fields=[
                ('lva_cdgo', models.AutoField(db_column='LVA_CDGO', primary_key=True, serialize=False)),
                ('lva_nombre', models.CharField(db_column='LVA_NOMBRE', max_length=64)),
                ('lva_descr', models.CharField(blank=True, db_column='LVA_DESCR', max_length=256, null=True)),
                ('lva_estdo', models.CharField(db_column='LVA_ESTDO', max_length=1)),
            ],
            options={
                'db_table': 'lva_listavalor',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('ope_cdgo', models.AutoField(db_column='OPE_CDGO', primary_key=True, serialize=False)),
                ('ope_nombre', models.CharField(db_column='OPE_NOMBRE', max_length=64)),
                ('ope_identificacion', models.CharField(db_column='OPE_IDENTIFICACION', max_length=20, null=True, unique=True)),
                ('ope_passwd', models.CharField(db_column='OPE_PASSWD', max_length=256)),
                ('ope_estdo', models.CharField(db_column='OPE_ESTDO', default='A', max_length=1)),
            ],
            options={
                'db_table': 'ope_operador',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Satisfaccion',
            fields=[
                ('sat_cdgo', models.AutoField(db_column='SAT_CDGO', primary_key=True, serialize=False)),
                ('sat_calif', models.IntegerField(db_column='SAT_CALIF')),
                ('sat_cmntrio', models.TextField(blank=True, db_column='SAT_CMNTRIO', null=True)),
                ('sat_fecha', models.DateTimeField(auto_now_add=True, db_column='SAT_FECHA')),
            ],
            options={
                'db_table': 'sat_satisfaccion',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('srv_cdgo', models.AutoField(db_column='SRV_CDGO', primary_key=True, serialize=False)),
                ('srv_nombre', models.CharField(db_column='SRV_NOMBRE', max_length=128)),
                ('srv_tipo', models.CharField(db_column='SRV_TIPO', max_length=64)),
                ('srv_estdo', models.CharField(db_column='SRV_ESTDO', default='A', max_length=1)),
            ],
            options={
                'db_table': 'srv_servicio',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ListaValorDetalle',
            fields=[
                ('lvd_cdgo', models.AutoField(db_column='LVD_CDGO', primary_key=True, serialize=False)),
                ('lvd_valor', models.CharField(db_column='LVD_VALOR', max_length=32)),
                ('lvd_etiqta', models.CharField(db_column='LVD_ETIQTA', max_length=128)),
                ('lvd_estdo', models.CharField(db_column='LVD_ESTDO', max_length=1)),
                ('lva', models.ForeignKey(db_column='LVA_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.listavalor')),
            ],
            options={
                'db_table': 'lvd_listavalordetalle',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('atn_cdgo', models.AutoField(db_column='ATN_CDGO', primary_key=True, serialize=False)),
                ('atn_fecha', models.DateField(auto_now_add=True, db_column='ATN_FECHA')),
                ('atn_hrini', models.TimeField(auto_now_add=True, db_column='ATN_HRINI')),
                ('atn_hrfin', models.TimeField(blank=True, db_column='ATN_HRFIN', null=True)),
                ('atn_estdo', models.CharField(db_column='ATN_ESTDO', default='A', max_length=1)),
                ('ciu', models.ForeignKey(db_column='CIU_CDGO', on_delete=django.db.models.deletion.CASCADE, to='modulo_puntos_app.ciudadano')),
                ('ope', models.ForeignKey(db_column='OPE_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.operador')),
                ('sat', models.ForeignKey(db_column='SAT_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.satisfaccion')),
                ('srv', models.ForeignKey(db_column='SRV_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.servicio')),
            ],
            options={
                'db_table': 'atn_atencion',
                'managed': True,
            },
        ),
    ]
