# Generated by Django 5.2.12 on 2026-04-21 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(blank=True, max_length=128, null=True, verbose_name='Usuario')),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('EXPORT', 'Exportación de datos'), ('OTHER', 'Otra acción')], max_length=32, verbose_name='Acción')),
                ('modelo_afectado', models.CharField(blank=True, max_length=128, null=True, verbose_name='Modelo Afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='ID del Objeto')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('direccion_ip', models.CharField(blank=True, max_length=45, null=True, verbose_name='Dirección IP')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha y Hora')),
            ],
            options={
                'verbose_name': 'Registro de Auditoría',
                'verbose_name_plural': 'Registros de Auditoría',
                'db_table': 'pvd_auditoria',
                'ordering': ['-fecha_accion'],
            },
        ),
        migrations.CreateModel(
            name='ListaValor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64, verbose_name='Nombre')),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True, verbose_name='Descripción')),
                ('estado', models.CharField(max_length=1, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Lista de Valor',
                'verbose_name_plural': 'Listas de Valor',
                'db_table': 'pvd_listas_valor',
            },
        ),
        migrations.CreateModel(
            name='PrestamoRecurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_entrega', models.DateTimeField(verbose_name='Fecha de Entrega')),
                ('fecha_devolucion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Devolución')),
                ('observaciones', models.CharField(blank=True, max_length=512, null=True, verbose_name='Observaciones')),
            ],
            options={
                'verbose_name': 'Préstamo de Recurso',
                'verbose_name_plural': 'Préstamos de Recursos',
                'db_table': 'pvd_prestamos',
            },
        ),
        migrations.CreateModel(
            name='PuntoViveDigital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=128, null=True, verbose_name='Nombre del Punto Vive Digital')),
                ('direccion', models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=64, null=True, verbose_name='Barrio/Vereda')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono')),
                ('correo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Correo electrónico')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'En mantenimiento')], default='A', max_length=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción/Notas')),
            ],
            options={
                'verbose_name': 'Punto Vive Digital',
                'verbose_name_plural': 'Puntos Vive Digital',
                'db_table': 'pvd_puntos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nombre')),
                ('contrasena', models.CharField(blank=True, max_length=256, null=True, verbose_name='Contraseña')),
                ('estado', models.CharField(blank=True, max_length=1, null=True, verbose_name='Estado')),
            ],
            options={
                'verbose_name': 'Usuario del Sistema',
                'verbose_name_plural': 'Usuarios del Sistema',
                'db_table': 'pvd_usuarios_legacy',
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Número de Documento')),
                ('primer_nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(blank=True, max_length=64, null=True, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=64, null=True, verbose_name='Segundo Apellido')),
                ('correo', models.CharField(blank=True, max_length=128, null=True, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono')),
                ('estado', models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, null=True, verbose_name='Estado')),
                ('punto_vive_digital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'db_table': 'pvd_operadores',
            },
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(blank=True, max_length=32, null=True, verbose_name='Tipo de Documento')),
                ('numero_documento', models.CharField(blank=True, max_length=32, null=True, unique=True, verbose_name='Número de Documento')),
                ('primer_nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Primer Nombre')),
                ('segundo_nombre', models.CharField(blank=True, max_length=64, null=True, verbose_name='Segundo Nombre')),
                ('primer_apellido', models.CharField(blank=True, max_length=64, null=True, verbose_name='Primer Apellido')),
                ('segundo_apellido', models.CharField(blank=True, max_length=64, null=True, verbose_name='Segundo Apellido')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento')),
                ('genero', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=32, null=True, verbose_name='Género')),
                ('etnia', models.CharField(blank=True, max_length=64, null=True, verbose_name='Etnia')),
                ('nivel_educativo', models.CharField(blank=True, max_length=64, null=True, verbose_name='Nivel Educativo')),
                ('ocupacion', models.CharField(blank=True, max_length=64, null=True, verbose_name='Ocupación')),
                ('tiene_discapacidad', models.BooleanField(default=False, verbose_name='Tiene Discapacidad')),
                ('descripcion_discapacidad', models.CharField(blank=True, max_length=128, null=True, verbose_name='Descripción Discapacidad')),
                ('direccion', models.CharField(blank=True, max_length=128, null=True, verbose_name='Dirección')),
                ('barrio', models.CharField(blank=True, max_length=64, null=True, verbose_name='Barrio')),
                ('zona_rural', models.CharField(blank=True, max_length=64, null=True, verbose_name='Zona Rural')),
                ('estrato', models.IntegerField(default=1, verbose_name='Estrato Socioeconómico')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('correo', models.CharField(blank=True, default='', max_length=128, verbose_name='Correo Electrónico')),
                ('telefono', models.CharField(blank=True, max_length=32, null=True, verbose_name='Teléfono')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Fecha de Registro')),
                ('punto_vive_digital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
            ],
            options={
                'verbose_name': 'Ciudadano',
                'verbose_name_plural': 'Ciudadanos',
                'db_table': 'pvd_ciudadanos',
            },
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Atención')),
                ('hora_inicio', models.TimeField(verbose_name='Hora de Inicio')),
                ('hora_fin', models.TimeField(blank=True, null=True, verbose_name='Hora de Finalización')),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('F', 'Finalizada'), ('C', 'Cancelada')], default='P', max_length=1, verbose_name='Estado')),
                ('observaciones', models.CharField(blank=True, max_length=512, null=True, verbose_name='Observaciones')),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.ciudadano', verbose_name='Ciudadano')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.operador', verbose_name='Operador')),
                ('prestamo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.prestamorecurso', verbose_name='Préstamo')),
                ('punto_vive_digital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
            ],
            options={
                'verbose_name': 'Atención',
                'verbose_name_plural': 'Atenciones',
                'db_table': 'pvd_atenciones',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=64, verbose_name='Tipo de Recurso')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], max_length=1, verbose_name='Estado')),
                ('punto_vive_digital', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
            ],
            options={
                'verbose_name': 'Recurso',
                'verbose_name_plural': 'Recursos',
                'db_table': 'pvd_recursos',
            },
        ),
        migrations.AddField(
            model_name='prestamorecurso',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.recurso', verbose_name='Recurso'),
        ),
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre de la Sala')),
                ('descripcion', models.TextField(blank=True, null=True, verbose_name='Descripción')),
                ('capacidad', models.IntegerField(blank=True, null=True, verbose_name='Capacidad')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'En mantenimiento')], default='A', max_length=1, verbose_name='Estado')),
                ('fecha_creacion', models.DateField(auto_now_add=True, null=True, verbose_name='Fecha de creación')),
                ('punto_vive_digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'pvd_salas',
                'ordering': ['punto_vive_digital', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Satisfaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(verbose_name='Calificación (1-5)')),
                ('comentario', models.CharField(blank=True, max_length=512, null=True, verbose_name='Comentario')),
                ('fecha', models.DateTimeField(verbose_name='Fecha de Encuesta')),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.atencion', verbose_name='Atención')),
            ],
            options={
                'verbose_name': 'Encuesta de Satisfacción',
                'verbose_name_plural': 'Encuestas de Satisfacción',
                'db_table': 'pvd_satisfaccion',
            },
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128, verbose_name='Nombre del Servicio')),
                ('descripcion', models.CharField(blank=True, max_length=512, null=True, verbose_name='Descripción')),
                ('tipo', models.CharField(max_length=64, verbose_name='Tipo de Servicio')),
                ('requiere_equipo', models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='¿Requiere Equipo?')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado')),
                ('atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.atencion', verbose_name='Atención')),
            ],
            options={
                'verbose_name': 'Servicio',
                'verbose_name_plural': 'Servicios',
                'db_table': 'pvd_servicios',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('superadmin', 'Superadministrador'), ('admin_tic', 'Administrador TIC'), ('admin_pvd', 'Administrador PVD'), ('operador', 'Operador')], default='operador', max_length=20, verbose_name='Rol del Usuario')),
                ('punto_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='PVD Asignado')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pvd_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'db_table': 'pvd_perfiles',
            },
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['primer_nombre', 'primer_apellido'], name='idx_ciu_nombres'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['punto_vive_digital', 'estado'], name='idx_ciu_pvd_estdo'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['fecha_nacimiento'], name='idx_ciu_fchancm'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['direccion'], name='idx_ciu_dircion'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['punto_vive_digital', 'fecha'], name='idx_atn_pvd_fecha'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['estado'], name='idx_atn_estdo'),
        ),
        migrations.AlterUniqueTogether(
            name='sala',
            unique_together={('punto_vive_digital', 'nombre')},
        ),
    ]
