# Generated by Django 5.2.12 on 2026-04-07 08:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrestamoRecurso',
            fields=[
                ('prs_cdgo', models.AutoField(db_column='PRS_CDGO', primary_key=True, serialize=False)),
                ('prs_fchent', models.DateTimeField(db_column='PRS_FCHENT')),
                ('prs_fchdev', models.DateTimeField(blank=True, db_column='PRS_FCHDEV', null=True)),
                ('prs_obs', models.CharField(blank=True, db_column='PRS_OBS', max_length=512, null=True)),
            ],
            options={
                'db_table': 'prs_prestamorecurso',
            },
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('rec_cdgo', models.IntegerField(db_column='REC_CDGO', primary_key=True, serialize=False)),
                ('rec_tipo', models.CharField(db_column='REC_TIPO', max_length=64)),
                ('rec_estdo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='REC_ESTDO', max_length=1)),
            ],
            options={
                'db_table': 'rec_recurso',
            },
        ),
        migrations.CreateModel(
            name='UsuarioSistema',
            fields=[
                ('usu_cdgo', models.AutoField(db_column='USU_CDGO', primary_key=True, serialize=False)),
                ('usu_nombre', models.CharField(blank=True, db_column='USU_NOMBRE', max_length=64, null=True)),
                ('usu_passwd', models.CharField(blank=True, db_column='USU_PASSWD', max_length=256, null=True)),
                ('usu_estdo', models.CharField(blank=True, db_column='USU_ESTDO', max_length=1, null=True)),
            ],
            options={
                'db_table': 'usu_usuariosistema',
            },
        ),
        migrations.AlterModelOptions(
            name='atencion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ciudadano',
            options={},
        ),
        migrations.AlterModelOptions(
            name='listavalor',
            options={},
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={},
        ),
        migrations.AlterModelOptions(
            name='satisfaccion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={},
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='ciu',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='ope',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='sat',
        ),
        migrations.RemoveField(
            model_name='atencion',
            name='srv',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='ope_cdgo',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='ope_estdo',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='ope_identificacion',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='ope_nombre',
        ),
        migrations.RemoveField(
            model_name='operador',
            name='ope_passwd',
        ),
        migrations.AddField(
            model_name='atencion',
            name='atn_obs',
            field=models.CharField(blank=True, db_column='ATN_OBS', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='atencion',
            name='ciu_cdgo',
            field=models.ForeignKey(blank=True, db_column='CIU_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.ciudadano'),
        ),
        migrations.AddField(
            model_name='atencion',
            name='opr_cdgo',
            field=models.ForeignKey(blank=True, db_column='OPR_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.operador'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ciu_barrio',
            field=models.CharField(blank=True, db_column='CIU_BARRIO', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ciu_desc_discapacidad',
            field=models.CharField(blank=True, db_column='CIU_DESC_DISCAPACIDAD', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ciu_dircion',
            field=models.CharField(blank=True, db_column='CIU_DIRCION', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ciu_zrural',
            field=models.CharField(blank=True, db_column='CIU_ZRURAL', max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_aplldos',
            field=models.CharField(blank=True, db_column='OPR_APLLDOS', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_cdgo',
            field=models.AutoField(db_column='OPR_CDGO', primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_email',
            field=models.CharField(blank=True, db_column='OPR_EMAIL', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_estdo',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='OPR_ESTDO', max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_nmbres',
            field=models.CharField(blank=True, db_column='OPR_NMBRES', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_numdoc',
            field=models.CharField(blank=True, db_column='OPR_NUMDOC', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_tlfno',
            field=models.CharField(blank=True, db_column='OPR_TLFNO', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='operador',
            name='opr_tpodoc',
            field=models.CharField(blank=True, db_column='OPR_TPODOC', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='satisfaccion',
            name='atn_cdgo',
            field=models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.atencion'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='atn_cdgo',
            field=models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.atencion'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='srv_descr',
            field=models.CharField(blank=True, db_column='SRV_DESCR', max_length=512, null=True),
        ),
        migrations.AddField(
            model_name='servicio',
            name='srv_reqeqp',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], db_column='SRV_REQEQP', default='N', max_length=1),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_estdo',
            field=models.CharField(choices=[('P', 'Pendiente'), ('F', 'Finalizada'), ('C', 'Cancelada')], db_column='ATN_ESTDO', default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_fecha',
            field=models.DateField(db_column='ATN_FECHA'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_hrini',
            field=models.TimeField(db_column='ATN_HRINI'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_aplldos',
            field=models.CharField(blank=True, db_column='CIU_APLLDOS', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_email',
            field=models.CharField(blank=True, db_column='CIU_EMAIL', default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_estdo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='CIU_ESTDO', default='A', max_length=1),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_estrato',
            field=models.IntegerField(db_column='CIU_ESTRATO', default=1),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_fchancm',
            field=models.DateField(blank=True, db_column='CIU_FCHANCM', null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_genro',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], db_column='CIU_GENRO', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_nmbres',
            field=models.CharField(blank=True, db_column='CIU_NMBRES', max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_numdoc',
            field=models.CharField(blank=True, db_column='CIU_NUMDOC', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_tpodoc',
            field=models.CharField(blank=True, db_column='CIU_TPODOC', max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='listavalor',
            name='lva_cdgo',
            field=models.IntegerField(db_column='LVA_CDGO', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='sat_cmntrio',
            field=models.CharField(blank=True, db_column='SAT_CMNTRIO', max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='sat_fecha',
            field=models.DateTimeField(db_column='SAT_FECHA'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='srv_estdo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='SRV_ESTDO', default='A', max_length=1),
        ),
        migrations.AlterModelTable(
            name='operador',
            table='opr_operador',
        ),
        migrations.AddField(
            model_name='atencion',
            name='prs_cdgo',
            field=models.ForeignKey(blank=True, db_column='PRS_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.prestamorecurso'),
        ),
        migrations.CreateModel(
            name='PuntoViveDigital',
            fields=[
                ('pvd_cdgo', models.IntegerField(db_column='PVD_CDGO', primary_key=True, serialize=False)),
                ('pvd_dircion', models.CharField(db_column='PVD_DIRCION', max_length=128)),
                ('pvd_barrio', models.CharField(db_column='PVD_BARRIO', max_length=64)),
                ('pvd_estdo', models.CharField(db_column='PVD_ESTDO', max_length=1)),
                ('pvd_correo', models.CharField(db_column='PVD_CORREO', max_length=128)),
                ('atn_cdgo', models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.atencion')),
                ('opr_cdgo', models.ForeignKey(blank=True, db_column='OPR_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.operador')),
                ('srv_cdgo', models.ForeignKey(blank=True, db_column='SRV_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.servicio')),
                ('rec_cdgo', models.ForeignKey(blank=True, db_column='REC_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.recurso')),
            ],
            options={
                'db_table': 'pvd_puntovivedigital',
            },
        ),
        migrations.AddField(
            model_name='prestamorecurso',
            name='rec_cdgo',
            field=models.ForeignKey(blank=True, db_column='REC_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.recurso'),
        ),
        migrations.AddField(
            model_name='operador',
            name='usu_cdgo',
            field=models.ForeignKey(blank=True, db_column='USU_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.usuariosistema'),
        ),
        migrations.DeleteModel(
            name='ListaValorDetalle',
        ),
    ]
