# Generated by Django 5.2.12 on 2026-04-21 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='atencion',
            table='pvd_atenciones',
        ),
        migrations.AlterModelTable(
            name='auditoriaaccion',
            table='pvd_auditoria',
        ),
        migrations.AlterModelTable(
            name='ciudadano',
            table='pvd_ciudadanos',
        ),
        migrations.AlterModelTable(
            name='listavalor',
            table='pvd_listas_valor',
        ),
        migrations.AlterModelTable(
            name='operador',
            table='pvd_operadores',
        ),
        migrations.AlterModelTable(
            name='prestamorecurso',
            table='pvd_prestamos',
        ),
        migrations.AlterModelTable(
            name='puntovivedigital',
            table='pvd_puntos',
        ),
        migrations.AlterModelTable(
            name='recurso',
            table='pvd_recursos',
        ),
        migrations.AlterModelTable(
            name='sala',
            table='pvd_salas',
        ),
        migrations.AlterModelTable(
            name='satisfaccion',
            table='pvd_satisfaccion',
        ),
        migrations.AlterModelTable(
            name='servicio',
            table='pvd_servicios',
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='pvd_perfiles',
        ),
        migrations.AlterModelTable(
            name='usuariosistema',
            table='pvd_usuarios_legacy',
        ),
    ]
