# Generated by Django 5.2.12 on 2026-04-07 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0002_prestamorecurso_recurso_usuariosistema_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaAccion',
            fields=[
                ('aud_cdgo', models.AutoField(db_column='AUD_CDGO', primary_key=True, serialize=False)),
                ('usuario', models.CharField(blank=True, db_column='AUD_USUARIO', max_length=128, null=True)),
                ('accion', models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('EXPORT', 'Exportación de datos'), ('OTHER', 'Otra acción')], db_column='AUD_ACCION', max_length=32)),
                ('modelo_afectado', models.CharField(blank=True, db_column='AUD_MODELO', max_length=128, null=True)),
                ('objeto_id', models.CharField(blank=True, db_column='AUD_OBJETO_ID', max_length=128, null=True)),
                ('descripcion', models.TextField(blank=True, db_column='AUD_DESCRIPCION', null=True)),
                ('ip_address', models.CharField(blank=True, db_column='AUD_IP', max_length=45, null=True)),
                ('fecha_accion', models.DateTimeField(auto_now_add=True, db_column='AUD_FECHA')),
            ],
            options={
                'verbose_name': 'Registro de auditoría',
                'verbose_name_plural': 'Registros de auditoría',
                'db_table': 'aud_auditoria_accion',
                'ordering': ['-fecha_accion'],
            },
        ),
    ]
