# Generated by Django 5.2.12 on 2026-04-07 09:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0003_auditoriaaccion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puntovivedigital',
            options={'ordering': ['pvd_nombre'], 'verbose_name': 'Punto Vive Digital', 'verbose_name_plural': 'Puntos Vive Digital'},
        ),
        migrations.RemoveField(
            model_name='puntovivedigital',
            name='atn_cdgo',
        ),
        migrations.RemoveField(
            model_name='puntovivedigital',
            name='opr_cdgo',
        ),
        migrations.RemoveField(
            model_name='puntovivedigital',
            name='rec_cdgo',
        ),
        migrations.RemoveField(
            model_name='puntovivedigital',
            name='srv_cdgo',
        ),
        migrations.AddField(
            model_name='atencion',
            name='pvd_cdgo',
            field=models.ForeignKey(blank=True, db_column='PVD_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='pvd_cdgo',
            field=models.ForeignKey(blank=True, db_column='PVD_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital'),
        ),
        migrations.AddField(
            model_name='operador',
            name='pvd_cdgo',
            field=models.ForeignKey(blank=True, db_column='PVD_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital'),
        ),
        migrations.AddField(
            model_name='puntovivedigital',
            name='pvd_descripcion',
            field=models.TextField(blank=True, db_column='PVD_DESCRIPCION', null=True, verbose_name='Descripción/Notas'),
        ),
        migrations.AddField(
            model_name='puntovivedigital',
            name='pvd_fch_crea',
            field=models.DateField(auto_now_add=True, db_column='PVD_FCH_CREA', null=True, verbose_name='Fecha de creación'),
        ),
        migrations.AddField(
            model_name='puntovivedigital',
            name='pvd_nombre',
            field=models.CharField(db_column='PVD_NOMBRE', max_length=128, null=True, verbose_name='Nombre del Punto Vive Digital'),
        ),
        migrations.AddField(
            model_name='puntovivedigital',
            name='pvd_telefono',
            field=models.CharField(blank=True, db_column='PVD_TELEFONO', max_length=32, null=True, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='recurso',
            name='pvd_cdgo',
            field=models.ForeignKey(blank=True, db_column='PVD_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_barrio',
            field=models.CharField(db_column='PVD_BARRIO', max_length=64, null=True, verbose_name='Barrio/Vereda'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_cdgo',
            field=models.AutoField(db_column='PVD_CDGO', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_correo',
            field=models.CharField(blank=True, db_column='PVD_CORREO', max_length=128, null=True, verbose_name='Correo electrónico'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_dircion',
            field=models.CharField(db_column='PVD_DIRCION', max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_estdo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'En mantenimiento')], db_column='PVD_ESTDO', default='A', max_length=1, verbose_name='Estado'),
        ),
    ]
