# Generated by Django 6.0.3 on 2026-04-07 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0005_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atencion',
            options={'verbose_name': 'Atención', 'verbose_name_plural': 'Atenciones'},
        ),
        migrations.AlterModelOptions(
            name='auditoriaaccion',
            options={'ordering': ['-fecha_accion'], 'verbose_name': 'Registro de Auditoría', 'verbose_name_plural': 'Registros de Auditoría'},
        ),
        migrations.AlterModelOptions(
            name='ciudadano',
            options={'verbose_name': 'Ciudadano', 'verbose_name_plural': 'Ciudadanos'},
        ),
        migrations.AlterModelOptions(
            name='listavalor',
            options={'verbose_name': 'Lista de Valor', 'verbose_name_plural': 'Listas de Valor'},
        ),
        migrations.AlterModelOptions(
            name='operador',
            options={'verbose_name': 'Operador', 'verbose_name_plural': 'Operadores'},
        ),
        migrations.AlterModelOptions(
            name='prestamorecurso',
            options={'verbose_name': 'Préstamo de Recurso', 'verbose_name_plural': 'Préstamos de Recursos'},
        ),
        migrations.AlterModelOptions(
            name='recurso',
            options={'verbose_name': 'Recurso', 'verbose_name_plural': 'Recursos'},
        ),
        migrations.AlterModelOptions(
            name='satisfaccion',
            options={'verbose_name': 'Encuesta de Satisfacción', 'verbose_name_plural': 'Encuestas de Satisfacción'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='usuariosistema',
            options={'verbose_name': 'Usuario del Sistema', 'verbose_name_plural': 'Usuarios del Sistema'},
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_estdo',
            field=models.CharField(choices=[('P', 'Pendiente'), ('F', 'Finalizada'), ('C', 'Cancelada')], db_column='ATN_ESTDO', default='P', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_fecha',
            field=models.DateField(db_column='ATN_FECHA', verbose_name='Fecha de Atención'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_hrfin',
            field=models.TimeField(blank=True, db_column='ATN_HRFIN', null=True, verbose_name='Hora de Finalización'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_hrini',
            field=models.TimeField(db_column='ATN_HRINI', verbose_name='Hora de Inicio'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='atn_obs',
            field=models.CharField(blank=True, db_column='ATN_OBS', max_length=512, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='ciu_cdgo',
            field=models.ForeignKey(blank=True, db_column='CIU_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='opr_cdgo',
            field=models.ForeignKey(blank=True, db_column='OPR_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.operador', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='prs_cdgo',
            field=models.ForeignKey(blank=True, db_column='PRS_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.prestamorecurso', verbose_name='Préstamo'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='accion',
            field=models.CharField(choices=[('CREATE', 'Creación'), ('UPDATE', 'Actualización'), ('DELETE', 'Eliminación'), ('LOGIN', 'Inicio de sesión'), ('LOGOUT', 'Cierre de sesión'), ('EXPORT', 'Exportación de datos'), ('OTHER', 'Otra acción')], db_column='AUD_ACCION', max_length=32, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='descripcion',
            field=models.TextField(blank=True, db_column='AUD_DESCRIPCION', null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='fecha_accion',
            field=models.DateTimeField(auto_now_add=True, db_column='AUD_FECHA', verbose_name='Fecha y Hora'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='ip_address',
            field=models.CharField(blank=True, db_column='AUD_IP', max_length=45, null=True, verbose_name='Dirección IP'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='modelo_afectado',
            field=models.CharField(blank=True, db_column='AUD_MODELO', max_length=128, null=True, verbose_name='Modelo Afectado'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='objeto_id',
            field=models.CharField(blank=True, db_column='AUD_OBJETO_ID', max_length=128, null=True, verbose_name='ID del Objeto'),
        ),
        migrations.AlterField(
            model_name='auditoriaaccion',
            name='usuario',
            field=models.CharField(blank=True, db_column='AUD_USUARIO', max_length=128, null=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_aplldos',
            field=models.CharField(blank=True, db_column='CIU_APLLDOS', max_length=128, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_barrio',
            field=models.CharField(blank=True, db_column='CIU_BARRIO', max_length=64, null=True, verbose_name='Barrio'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_desc_discapacidad',
            field=models.CharField(blank=True, db_column='CIU_DESC_DISCAPACIDAD', max_length=128, null=True, verbose_name='Descripción Discapacidad'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_dircion',
            field=models.CharField(blank=True, db_column='CIU_DIRCION', max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_discapacidad',
            field=models.BooleanField(db_column='CIU_DISCAPACIDAD', default=False, verbose_name='Tiene Discapacidad'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_email',
            field=models.CharField(blank=True, db_column='CIU_EMAIL', default='', max_length=128, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_estdo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='CIU_ESTDO', default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_estrato',
            field=models.IntegerField(db_column='CIU_ESTRATO', default=1, verbose_name='Estrato Socioeconómico'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_etnia',
            field=models.CharField(blank=True, db_column='CIU_ETNIA', max_length=64, null=True, verbose_name='Etnia'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_fchancm',
            field=models.DateField(blank=True, db_column='CIU_FCHANCM', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_genro',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], db_column='CIU_GENRO', max_length=32, null=True, verbose_name='Género'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_nmbres',
            field=models.CharField(blank=True, db_column='CIU_NMBRES', max_length=128, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_numdoc',
            field=models.CharField(blank=True, db_column='CIU_NUMDOC', max_length=32, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_nvleduc',
            field=models.CharField(blank=True, db_column='CIU_NVLEDUC', max_length=64, null=True, verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_ocpcion',
            field=models.CharField(blank=True, db_column='CIU_OCPCION', max_length=64, null=True, verbose_name='Ocupación'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_tlfno',
            field=models.CharField(blank=True, db_column='CIU_TLFNO', max_length=32, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_tpodoc',
            field=models.CharField(blank=True, db_column='CIU_TPODOC', max_length=32, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_zrural',
            field=models.CharField(blank=True, db_column='CIU_ZRURAL', max_length=64, null=True, verbose_name='Zona Rural'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_aplldos',
            field=models.CharField(blank=True, db_column='OPR_APLLDOS', max_length=128, null=True, verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_email',
            field=models.CharField(blank=True, db_column='OPR_EMAIL', max_length=128, null=True, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_estdo',
            field=models.CharField(blank=True, choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='OPR_ESTDO', max_length=1, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_nmbres',
            field=models.CharField(blank=True, db_column='OPR_NMBRES', max_length=128, null=True, verbose_name='Nombres'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_numdoc',
            field=models.CharField(blank=True, db_column='OPR_NUMDOC', max_length=32, null=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_tlfno',
            field=models.CharField(blank=True, db_column='OPR_TLFNO', max_length=32, null=True, verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_tpodoc',
            field=models.CharField(blank=True, db_column='OPR_TPODOC', max_length=32, null=True, verbose_name='Tipo de Documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='usu_cdgo',
            field=models.ForeignKey(blank=True, db_column='USU_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.usuariosistema', verbose_name='Usuario del Sistema'),
        ),
        migrations.AlterField(
            model_name='prestamorecurso',
            name='prs_fchdev',
            field=models.DateTimeField(blank=True, db_column='PRS_FCHDEV', null=True, verbose_name='Fecha de Devolución'),
        ),
        migrations.AlterField(
            model_name='prestamorecurso',
            name='prs_fchent',
            field=models.DateTimeField(db_column='PRS_FCHENT', verbose_name='Fecha de Entrega'),
        ),
        migrations.AlterField(
            model_name='prestamorecurso',
            name='prs_obs',
            field=models.CharField(blank=True, db_column='PRS_OBS', max_length=512, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='prestamorecurso',
            name='rec_cdgo',
            field=models.ForeignKey(blank=True, db_column='REC_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.recurso', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_barrio',
            field=models.CharField(blank=True, db_column='PVD_BARRIO', max_length=64, null=True, verbose_name='Barrio/Vereda'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_dircion',
            field=models.CharField(blank=True, db_column='PVD_DIRCION', max_length=128, null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='pvd_nombre',
            field=models.CharField(blank=True, db_column='PVD_NOMBRE', max_length=128, null=True, verbose_name='Nombre del Punto Vive Digital'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='rec_estdo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='REC_ESTDO', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='recurso',
            name='rec_tipo',
            field=models.CharField(db_column='REC_TIPO', max_length=64, verbose_name='Tipo de Recurso'),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='atn_cdgo',
            field=models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.atencion', verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='sat_calif',
            field=models.IntegerField(db_column='SAT_CALIF', verbose_name='Calificación (1-5)'),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='sat_cmntrio',
            field=models.CharField(blank=True, db_column='SAT_CMNTRIO', max_length=512, null=True, verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='sat_fecha',
            field=models.DateTimeField(db_column='SAT_FECHA', verbose_name='Fecha de Encuesta'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='atn_cdgo',
            field=models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='modulo_puntos_app.atencion', verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='srv_descr',
            field=models.CharField(blank=True, db_column='SRV_DESCR', max_length=512, null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='srv_estdo',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo')], db_column='SRV_ESTDO', default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='srv_nombre',
            field=models.CharField(db_column='SRV_NOMBRE', max_length=128, verbose_name='Nombre del Servicio'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='srv_reqeqp',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], db_column='SRV_REQEQP', default='N', max_length=1, verbose_name='¿Requiere Equipo?'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='srv_tipo',
            field=models.CharField(db_column='SRV_TIPO', max_length=64, verbose_name='Tipo de Servicio'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pvd_profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
    ]
