# Generated by Django 6.0.3 on 2026-04-07 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0006_alter_atencion_options_alter_auditoriaaccion_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sala',
            fields=[
                ('sala_cdgo', models.AutoField(db_column='SALA_CDGO', primary_key=True, serialize=False)),
                ('sala_nombre', models.CharField(db_column='SALA_NOMBRE', max_length=128, verbose_name='Nombre de la Sala')),
                ('sala_descr', models.TextField(blank=True, db_column='SALA_DESCR', null=True, verbose_name='Descripción')),
                ('sala_capacidad', models.IntegerField(blank=True, db_column='SALA_CAPACIDAD', null=True, verbose_name='Capacidad')),
                ('sala_estdo', models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('M', 'En mantenimiento')], db_column='SALA_ESTDO', default='A', max_length=1, verbose_name='Estado')),
                ('sala_fch_crea', models.DateField(auto_now_add=True, db_column='SALA_FCH_CREA', null=True, verbose_name='Fecha de creación')),
                ('pvd_cdgo', models.ForeignKey(db_column='PVD_CDGO', on_delete=django.db.models.deletion.CASCADE, to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
            ],
            options={
                'verbose_name': 'Sala',
                'verbose_name_plural': 'Salas',
                'db_table': 'sala_sala',
                'ordering': ['pvd_cdgo', 'sala_nombre'],
                'unique_together': {('pvd_cdgo', 'sala_nombre')},
            },
        ),
    ]
