# Generated by Django 5.2.12 on 2026-04-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0007_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='ciu_fecha_registro',
            field=models.DateTimeField(auto_now_add=True, db_column='CIU_FECHA_REGISTRO', null=True, verbose_name='Fecha de Registro'),
        ),
        migrations.AddField(
            model_name='ciudadano',
            name='ciu_pendiente_aprobacion',
            field=models.BooleanField(db_column='CIU_PENDIENTE_APROBACION', default=False, verbose_name='Pendiente de Aprobación'),
        ),
    ]
