# Generated by Django 5.2.12 on 2026-04-23 19:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0008_puntovivedigital_admin_a_cargo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='permisorol',
            name='uq_permiso_rol',
        ),
        migrations.RemoveConstraint(
            model_name='permisousuario',
            name='uq_permiso_usuario',
        ),
        migrations.AlterField(
            model_name='habilitacionsala',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterUniqueTogether(
            name='permisorol',
            unique_together={('rol', 'permiso')},
        ),
        migrations.AlterUniqueTogether(
            name='permisousuario',
            unique_together={('usuario', 'permiso')},
        ),
    ]
