# Generated by Django 6.0.3 on 2026-04-20 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0008_ciudadano_ciu_fecha_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atencion',
            name='ciu_cdgo',
            field=models.ForeignKey(blank=True, db_column='CIU_CDGO', null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='opr_cdgo',
            field=models.ForeignKey(blank=True, db_column='OPR_CDGO', null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.operador', verbose_name='Operador'),
        ),
        migrations.AlterField(
            model_name='atencion',
            name='prs_cdgo',
            field=models.ForeignKey(blank=True, db_column='PRS_CDGO', null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.prestamorecurso', verbose_name='Préstamo'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='ciu_numdoc',
            field=models.CharField(blank=True, db_column='CIU_NUMDOC', max_length=32, null=True, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='operador',
            name='opr_numdoc',
            field=models.CharField(blank=True, db_column='OPR_NUMDOC', max_length=32, null=True, unique=True, verbose_name='Número de Documento'),
        ),
        migrations.AlterField(
            model_name='prestamorecurso',
            name='rec_cdgo',
            field=models.ForeignKey(blank=True, db_column='REC_CDGO', null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.recurso', verbose_name='Recurso'),
        ),
        migrations.AlterField(
            model_name='satisfaccion',
            name='atn_cdgo',
            field=models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.atencion', verbose_name='Atención'),
        ),
        migrations.AlterField(
            model_name='servicio',
            name='atn_cdgo',
            field=models.ForeignKey(blank=True, db_column='ATN_CDGO', null=True, on_delete=django.db.models.deletion.PROTECT, to='modulo_puntos_app.atencion', verbose_name='Atención'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['pvd_cdgo', 'atn_fecha'], name='idx_atn_pvd_fecha'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['atn_estdo'], name='idx_atn_estdo'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['ciu_nmbres', 'ciu_aplldos'], name='idx_ciu_nombres'),
        ),
        migrations.AddIndex(
            model_name='ciudadano',
            index=models.Index(fields=['pvd_cdgo', 'ciu_estdo'], name='idx_ciu_pvd_estdo'),
        ),
    ]
