# Generated by Django 5.2.12 on 2026-05-08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """
    Nota histórica: esta migración ya está marcada como aplicada en la base de
    datos real, así que Django nunca la vuelve a ejecutar ahí — el contenido de
    abajo sólo importa para construir una base de datos nueva desde cero
    (pruebas automatizadas, CI, un entorno de desarrollo nuevo).

    Originalmente estas operaciones estaban envueltas en
    SeparateDatabaseAndState con database_operations=[] (un parche puntual de
    cuando un primer intento fallido ya había creado la tabla a mano). Eso
    dejaba el "estado" de Django creyendo que la tabla y los demás cambios
    existían sin ejecutarlos de verdad, así que una base de datos nueva se
    rompía al llegar aquí (la tabla nunca se creaba). Se dejan como
    operaciones normales para que el historial se pueda reproducir igual en
    cualquier base de datos.
    """

    dependencies = [
        ('modulo_puntos_app', '0019_seed_permisos_granulares'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicioPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del servicio')),
                ('icono', models.CharField(default='⚙️', max_length=20, verbose_name='Icono (emoji)')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('incluye', models.JSONField(default=list, verbose_name='Qué incluye')),
                ('habilitado', models.BooleanField(default=True, verbose_name='Habilitado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Servicio Personalizado',
                'verbose_name_plural': 'Servicios Personalizados',
                'db_table': 'pvd_servicios_personalizados',
                'ordering': ['nombre'],
            },
        ),
        migrations.AlterModelOptions(
            name='modulohabilitado',
            options={'verbose_name': 'Módulo Habilitado', 'verbose_name_plural': 'Módulos Habilitados'},
        ),
        migrations.RemoveConstraint(model_name='asistenciasesion', name='uniq_asistencia_sesion_ciudadano'),
        migrations.RemoveConstraint(model_name='inscripcioncurso', name='uniq_inscripcion_curso_ciudadano'),
        migrations.RemoveConstraint(model_name='sesioncurso', name='uniq_curso_sesion'),
        migrations.AlterField(
            model_name='modulohabilitado',
            name='modulo',
            field=models.CharField(choices=[('atencion_ciudadana', 'Atención ciudadana'), ('recursos_salas', 'Recursos y Salas'), ('cursos_talleres', 'Cursos y Talleres'), ('mantenimiento', 'Mantenimiento de equipos'), ('reportes', 'Reportes y exportaciones')], max_length=32, verbose_name='Módulo'),
        ),
        migrations.AlterField(
            model_name='modulohabilitado',
            name='punto_vive_digital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modulos_habilitados', to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital'),
        ),
        migrations.AlterUniqueTogether(name='asistenciasesion', unique_together={('sesion', 'ciudadano')}),
        migrations.AlterUniqueTogether(name='inscripcioncurso', unique_together={('curso', 'ciudadano')}),
        migrations.AlterUniqueTogether(name='sesioncurso', unique_together={('curso', 'numero_sesion')}),
        migrations.AddField(
            model_name='serviciopersonalizado',
            name='punto_vive_digital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios_personalizados', to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital'),
        ),
    ]
