# Generated by Django 5.2.12 on 2026-05-08 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0020_servicio_personalizado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviciopersonalizado',
            name='incluye',
        ),
        migrations.AddField(
            model_name='serviciopersonalizado',
            name='incluye_extra',
            field=models.JSONField(default=list, verbose_name='Ítems adicionales descriptivos'),
        ),
        migrations.AddField(
            model_name='serviciopersonalizado',
            name='modulos_sistema',
            field=models.JSONField(default=list, verbose_name='Módulos del sistema que activa'),
        ),
    ]
