# Generated by Django 5.2.12 on 2026-05-08 03:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0021_servicios_modulos_sistema'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del ítem')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='Descripción')),
                ('cantidad_total', models.PositiveIntegerField(default=1, verbose_name='Cantidad total')),
                ('unidad', models.CharField(default='unidad', max_length=50, verbose_name='Nombre de la unidad')),
                ('activo', models.BooleanField(default=True, verbose_name='Activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='modulo_puntos_app.serviciopersonalizado', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Ítem de servicio',
                'verbose_name_plural': 'Ítems de servicio',
                'db_table': 'pvd_item_servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_persona', models.CharField(blank=True, max_length=100, verbose_name='Nombre (si no es ciudadano registrado)')),
                ('fecha_fin_esperada', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de devolución esperada')),
                ('fecha_fin_real', models.DateTimeField(blank=True, null=True, verbose_name='Fecha/hora de finalización real')),
                ('notas', models.TextField(blank=True, verbose_name='Notas')),
                ('estado', models.CharField(choices=[('A', 'Activo'), ('F', 'Finalizado'), ('C', 'Cancelado')], default='A', max_length=1, verbose_name='Estado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('ciudadano', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.ciudadano', verbose_name='Ciudadano')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='modulo_puntos_app.itemservicio', verbose_name='Ítem')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Registro de servicio',
                'verbose_name_plural': 'Registros de servicio',
                'db_table': 'pvd_registro_servicio',
                'ordering': ['-creado_en'],
            },
        ),
    ]
