# Generated by Django 5.2.12 on 2026-05-12 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0022_item_registro_servicio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='puntovivedigital',
            name='correo',
        ),
        migrations.RemoveField(
            model_name='puntovivedigital',
            name='telefono',
        ),
    ]
