# Generated by Django 5.2.12 on 2026-05-15 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0027_nuevos_modulos_funcion_plantillafuncion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='registrofuncion',
            name='encuesta_respuestas',
            field=models.JSONField(default=dict, verbose_name='Respuestas de encuesta'),
        ),
        migrations.AlterField(
            model_name='funcionservicio',
            name='estados',
            field=models.JSONField(default=list, verbose_name='Estados del proceso'),
        ),
        migrations.AlterField(
            model_name='funcionservicio',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='funcionservicio',
            name='mod_ciudadano',
            field=models.BooleanField(default=False, verbose_name='Módulo: Ciudadano'),
        ),
        migrations.AlterField(
            model_name='funcionservicio',
            name='mod_estados',
            field=models.BooleanField(default=False, verbose_name='Módulo: Estados'),
        ),
        migrations.AlterField(
            model_name='funcionservicio',
            name='mod_formulario',
            field=models.BooleanField(default=False, verbose_name='Módulo: Formulario'),
        ),
        migrations.AlterField(
            model_name='funcionservicio',
            name='mod_stock',
            field=models.BooleanField(default=False, verbose_name='Módulo: Inventario'),
        ),
        migrations.AlterField(
            model_name='plantillafuncion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrofuncion',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_funcion_creados', to=settings.AUTH_USER_MODEL, verbose_name='Creado por'),
        ),
        migrations.AlterField(
            model_name='registrofuncion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registrofuncion',
            name='stock_cantidad',
            field=models.PositiveIntegerField(default=1, verbose_name='Cantidad (ítem único)'),
        ),
    ]
