# Generated by Django 5.2.12 on 2026-05-15 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0028_encuesta_respuestas_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('I', 'Inactivo'), ('P', 'Pendiente')], default='A', max_length=1, verbose_name='Estado'),
        ),
        migrations.DeleteModel(
            name='PlantillaFuncion',
        ),
    ]
