# Generated by Django 5.2.12 on 2026-05-21 12:33
# Modified: use RunSQL IF EXISTS because these tables may not exist in the DB
# (migrations 0025+ that created them were never applied to production).

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0029_eliminar_plantilla_funcion'),
    ]

    state_operations = []

    operations = [
        # Eliminar tabla huérfana con FK a pvd_servicios_personalizados
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS pvd_entradas_servicio;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # Eliminar tablas del sistema de servicios personalizados / compositor
        # Usamos IF EXISTS porque las tablas pueden no existir en producción
        # si las migraciones que las crearon nunca fueron aplicadas.
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS pvd_registros_funcion;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS pvd_funciones_servicio;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS pvd_modulos_habilitados;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS pvd_servicios_personalizados;",
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
