# Generated by Django 6.0.4 on 2026-05-26 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0026_servicio_color_categoria_ciudadano'),
        ('modulo_puntos_app', '0029_eliminar_plantilla_funcion'),
    ]

    operations = [
    ]
