# Generated by Django 5.2.12 on 2026-05-21 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0033_puntovivedigital_modulos_habilitados'),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datos', models.JSONField(default=dict, verbose_name='Datos enviados')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
                ('atencion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_servicio', to='modulo_puntos_app.atencion', verbose_name='Atención')),
                ('servicio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respuestas', to='modulo_puntos_app.catalogoservicio', verbose_name='Servicio')),
            ],
            options={
                'verbose_name': 'Respuesta de servicio',
                'verbose_name_plural': 'Respuestas de servicios',
                'db_table': 'pvd_respuestas_servicio',
                'ordering': ['-enviado_en'],
            },
        ),
    ]
