# Generated by Django 5.2.12 on 2026-05-27 14:43
# Fixed: tables were partially cleaned up on the laptop before this migration
# was created, so the DB schema doesn't match Django's expected state.
# We use SeparateDatabaseAndState to sync Django's state and drop the tables
# using IF EXISTS to avoid errors on columns/tables that may already be gone.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0038_atencion_hora_inicio_nullable'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.AlterUniqueTogether(
                    name='pvdservicio',
                    unique_together=None,
                ),
                migrations.RemoveField(model_name='pvdservicio', name='servicio'),
                migrations.RemoveField(model_name='pvdservicio', name='pvd'),
                migrations.RemoveField(model_name='respuestaservicio', name='servicio'),
                migrations.RemoveField(model_name='respuestaservicio', name='atencion'),
                migrations.RemoveField(model_name='puntovivedigital', name='modulos_habilitados'),
                migrations.DeleteModel(name='CatalogoServicio'),
                migrations.DeleteModel(name='PVDServicio'),
                migrations.DeleteModel(name='RespuestaServicio'),
            ],
            database_operations=[
                migrations.RunSQL("SET FOREIGN_KEY_CHECKS = 0", ""),
                migrations.RunSQL("DROP TABLE IF EXISTS pvd_pvd_servicios", ""),
                migrations.RunSQL("DROP TABLE IF EXISTS pvd_catalogo_servicios", ""),
                migrations.RunSQL("DROP TABLE IF EXISTS pvd_respuestas_servicio", ""),
                migrations.RunSQL("DROP TABLE IF EXISTS pvd_pvd_puntos_modulos_habilitados", ""),
                migrations.RunSQL("SET FOREIGN_KEY_CHECKS = 1", ""),
            ],
        ),
    ]
