# Generated by Django 5.2.12 on 2026-05-27 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0039_remove_respuestaservicio_servicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='recurso',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.recurso', verbose_name='Recurso utilizado'),
        ),
    ]
