# Generated by Django 5.2.12 on 2026-05-28 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0040_servicio_recurso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('categoria', models.CharField(choices=[('ACT', 'Actividad'), ('CAP', 'Capacitación'), ('MAN', 'Mantenimiento'), ('EVE', 'Evento'), ('OTR', 'Otra')], default='ACT', max_length=3, verbose_name='Categoría')),
                ('fecha', models.DateField(verbose_name='Fecha de la evidencia')),
                ('imagen', models.ImageField(upload_to='evidencias/%Y/%m/', verbose_name='Imagen')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('punto_vive_digital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='modulo_puntos_app.puntovivedigital', verbose_name='Punto Vive Digital')),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evidencias_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Evidencia',
                'verbose_name_plural': 'Evidencias',
                'db_table': 'pvd_evidencias',
                'ordering': ['-fecha', '-fecha_registro'],
            },
        ),
    ]
