# Generated by Django 5.2.12 on 2026-05-28 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0041_add_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamorecurso',
            name='ciudadano',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.ciudadano', verbose_name='Ciudadano'),
        ),
        migrations.AddIndex(
            model_name='prestamorecurso',
            index=models.Index(fields=['recurso', 'fecha_entrega'], name='idx_prs_recurso_fecha'),
        ),
        migrations.AddIndex(
            model_name='prestamorecurso',
            index=models.Index(fields=['ciudadano'], name='idx_prs_ciudadano'),
        ),
        migrations.AddIndex(
            model_name='satisfaccion',
            index=models.Index(fields=['atencion'], name='idx_sat_atencion'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['atencion'], name='idx_srv_atencion'),
        ),
        migrations.AddIndex(
            model_name='servicio',
            index=models.Index(fields=['tipo'], name='idx_srv_tipo'),
        ),
    ]
