# Generated by Django 6.0.4 on 2026-06-02 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0042_fix_servicio_prestamo_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicio',
            name='estado',
            field=models.CharField(choices=[('A', 'Activo'), ('F', 'Finalizado'), ('I', 'Inactivo')], default='A', max_length=1, verbose_name='Estado'),
        ),
    ]
