# Generated by Django 6.0.4 on 2026-06-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0043_servicio_estado_finalizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='municipio',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Municipio de Residencia'),
        ),
    ]
