# Generated by Django 6.0.6 on 2026-06-16 19:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0044_ciudadano_municipio'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditoriaaccion',
            index=models.Index(fields=['fecha_accion'], name='idx_aud_fecha'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccion',
            index=models.Index(fields=['usuario'], name='idx_aud_usuario'),
        ),
        migrations.AddIndex(
            model_name='auditoriaaccion',
            index=models.Index(fields=['accion'], name='idx_aud_accion'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['punto_vive_digital', 'estado'], name='idx_crs_pvd_estdo'),
        ),
        migrations.AddIndex(
            model_name='curso',
            index=models.Index(fields=['fecha_inicio'], name='idx_crs_fecha'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['punto_vive_digital', 'fecha'], name='idx_evi_pvd_fecha'),
        ),
        migrations.AddIndex(
            model_name='evidencia',
            index=models.Index(fields=['categoria'], name='idx_evi_categoria'),
        ),
        migrations.AddIndex(
            model_name='mantenimientoequipo',
            index=models.Index(fields=['punto_vive_digital', 'fecha'], name='idx_mant_pvd_fecha'),
        ),
        migrations.AddIndex(
            model_name='recurso',
            index=models.Index(fields=['punto_vive_digital', 'estado'], name='idx_rec_pvd_estdo'),
        ),
    ]
