# Generated by Django 6.0.6 on 2026-06-24 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0045_indices_rendimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['ciudadano'], name='idx_atn_ciudadano'),
        ),
        migrations.AddIndex(
            model_name='atencion',
            index=models.Index(fields=['operador'], name='idx_atn_operador'),
        ),
        migrations.AddIndex(
            model_name='prestamorecurso',
            index=models.Index(fields=['fecha_devolucion'], name='idx_prs_devolucion'),
        ),
    ]
