# Generated by Django 6.0.6 on 2026-06-24 15:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0046_optimizar_indices'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='auditoriaaccion',
            index=models.Index(fields=['modelo_afectado'], name='idx_aud_modelo'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['rol'], name='idx_perfil_rol'),
        ),
        migrations.AddConstraint(
            model_name='satisfaccion',
            constraint=models.CheckConstraint(condition=models.Q(('calificacion__gte', 1), ('calificacion__lte', 5)), name='chk_sat_calificacion'),
        ),
    ]
