# Generated by Django 6.0.6 on 2026-07-02 19:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0050_drop_tablas_huerfanas_constructor_servicios'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='requiere_sala',
            field=models.CharField(choices=[('S', 'Sí'), ('N', 'No')], default='N', max_length=1, verbose_name='¿Requiere Sala?'),
        ),
        migrations.AddField(
            model_name='servicio',
            name='sala',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modulo_puntos_app.sala', verbose_name='Sala solicitada'),
        ),
    ]
