# Generated by Django 6.0.6 on 2026-07-07 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0052_satisfaccion_preguntas_encuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='ciudadano',
            name='autorizacion_datos',
            field=models.BooleanField(default=False, help_text='Autorización conforme a la Ley 1581 de 2012 (Habeas Data).', verbose_name='Autorización de tratamiento de datos personales'),
        ),
    ]
