# Generated by Django 6.0.6 on 2026-07-08 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0053_agregar_autorizacion_datos_ciudadano'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='codigo',
            field=models.CharField(blank=True, help_text='Identificador único del equipo dentro de su PVD (ej: LAP-001). Opcional.', max_length=64, null=True, verbose_name='Código del recurso'),
        ),
        migrations.AddConstraint(
            model_name='recurso',
            constraint=models.UniqueConstraint(fields=('punto_vive_digital', 'codigo'), name='uniq_recurso_pvd_codigo'),
        ),
    ]
