# Generated by Django 6.0.6 on 2026-07-09 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0054_recurso_codigo_unico_por_pvd'),
    ]

    operations = [
        migrations.AddField(
            model_name='habilitacionsala',
            name='asistentes',
            field=models.ManyToManyField(blank=True, related_name='habilitaciones_asistidas', to='modulo_puntos_app.ciudadano', verbose_name='Personas que ingresarán'),
        ),
        migrations.AlterField(
            model_name='habilitacionsala',
            name='solicitante',
            field=models.ForeignKey(help_text='Ciudadano responsable de la reserva.', on_delete=django.db.models.deletion.PROTECT, related_name='habilitaciones_solicitadas', to='modulo_puntos_app.ciudadano', verbose_name='Solicitante / Grupo'),
        ),
    ]
