# Generated by Django 6.0.7 on 2026-07-14 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modulo_puntos_app', '0057_permiso_eliminar_recurso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='correo',
            field=models.EmailField(blank=True, default='', max_length=128, verbose_name='Correo Electrónico'),
        ),
        migrations.AlterField(
            model_name='puntovivedigital',
            name='nombre',
            field=models.CharField(max_length=128, unique=True, verbose_name='Nombre del Punto Vive Digital'),
        ),
    ]
